version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - chatbot-network

  api:
    build: 
      context: .
      dockerfile: docker/Dockerfile.api
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - OLLAMA_HOST=http://ollama:11434
    depends_on:
      - ollama
    networks:
      - chatbot-network
    volumes:
      - .:/app
    deploy:
      resources:
        limits:
          memory: 4G

  main:
    build:
      context: .
      dockerfile: docker/Dockerfile.main
    ports:
      - "8501:8501"
    depends_on:
      - api
      - ollama
    environment:
      - PYTHONPATH=/app
      - OLLAMA_HOST=http://ollama:11434
    networks:
      - chatbot-network
    volumes:
      - .:/app
    deploy:
      resources:
        limits:
          memory: 2G

networks:
  chatbot-network:
    driver: bridge

volumes:
  ollama_data: